export default {
  getClasesVehiculo() {
    return [
      { label: "Bicicleta", value: "Bicicleta" },
      { label: "Bus", value: "Bus" },
      { label: "Bus (padrón)", value: "Bus (padrón)" },
      { label: "Bus articulado", value: "Bus articulado" },
      { label: "Buseta", value: "Buseta" },
      { label: "Escalera", value: "Escalera" },
      { label: "Microbús", value: "Microbús" },
      { label: "Tranvía", value: "Tranvía" },
      { label: "Camioneta", value: "Camioneta" },
      { label: "Camión", value: "Camión" },
      { label: "Camión Dobletroque", value: "Camión Dobletroque" },
      { label: "Camión Tanque", value: "Camión Tanque" },
      { label: "Camión Recolector", value: "Camión Recolector" },
      { label: "Furgón", value: "Furgón" },
      { label: "Grúa", value: "Grúa" },
      { label: "Mezcladora", value: "Mezcladora" },
      { label: "Tractocamión", value: "Tractocamión" },
      { label: "Remolque", value: "Remolque" },
      { label: "Automóvil", value: "Automóvil" },
      { label: "Camioneta Furgon", value: "Camioneta Furgon" },
      { label: "Campero", value: "Campero" },
      { label: "Taxi", value: "Taxi" },
      { label: "Abonadora", value: "Abonadora" },
      { label: "Bulldozer", value: "Bulldozer" },
      { label: "Carretilla Elevadora", value: "Carretilla Elevadora" },
      { label: "Compactadora", value: "Compactadora" },
      { label: "Máquina Barredora", value: "Máquina Barredora" },
      { label: "Maquinaria Industrial", value: "Maquinaria Industrial" },
      { label: "Minicargador", value: "Minicargador" },
      { label: "Montacarga", value: "Montacarga" },
      { label: "Retroexcavadora", value: "Retroexcavadora" },
      { label: "Ciclomotor", value: "Ciclomotor" },
      { label: "Cuatrimoto", value: "Cuatrimoto" },
      { label: "Motocarro", value: "Motocarro" },
      { label: "Motocicleta", value: "Motocicleta" },
      { label: "Motociclo", value: "Motociclo" },
      { label: "Motoneta", value: "Motoneta" },
      { label: "Mototriciclo", value: "Mototriciclo" },
      { label: "Triciclo", value: "Triciclo" },
      { label: "Tricimoto", value: "Tricimoto" },
      { label: "Ambulancia", value: "Ambulancia" },
      { label: "Tracción Animal", value: "Tracción Animal" },
      { label: "Patineta Eléctrica", value: "Patineta Eléctrica" },
      { label: "Lancha Turistica", value: "Lancha Turistica" },
      { label: "Monotín", value: "Monotín" },
      { label: "Metro cable", value: "Metro cable" },
      { label: "Volqueta", value: "Volqueta" },
      { label: "Patineta", value: "Patineta" },
      { label: "Silla de ruedas", value: "Silla de ruedas" }
    ];
  }
}
